export const adminQueryKeys = {
  me: ["admin", "me"] as const,
  dashboard: (range: string) => ["admin", "dashboard", range] as const,
  users: (params: unknown) => ["admin", "users", params] as const,
  user: (id: string) => ["admin", "users", id] as const,
  nutrition: (range: string) => ["admin", "nutrition", range] as const,
  fitness: (range: string) => ["admin", "fitness", range] as const,
  userFeatures: (id: string) => ["admin", "users", id, "features"] as const,
  exercises: (params: unknown) => ["admin", "exercises", params] as const,
  exercise: (id: string) => ["admin", "exercises", id] as const,
  aiOverview: (range: string) => ["admin", "ai", "overview", range] as const,
  aiRequests: (params: unknown) => ["admin", "ai", "requests", params] as const,
  aiRequest: (id: string) => ["admin", "ai", "requests", id] as const,
  calculatorsOverview: (range: string) => ["admin", "calculators", "overview", range] as const,
  calculatorsUsage: (params: unknown) => ["admin", "calculators", "usage", params] as const,
  conversations: (params: unknown) => ["admin", "conversations", params] as const,
  conversation: (id: string) => ["admin", "conversations", id] as const,
  analytics: (params: unknown) => ["admin", "analytics", params] as const,
  systemHealth: ["admin", "system", "health"] as const,
  systemLogs: (params: unknown) => ["admin", "system", "logs", params] as const,
  team: ["admin", "admin-users"] as const,
  teamMember: (id: string) => ["admin", "admin-users", id] as const,
  settings: ["admin", "settings"] as const,
};
